apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployments  # Corrected name with hyphen for better readability
  labels:
    type: my-app
spec:
  selector:
    matchLabels:
      env: production
  replicas: 4
  template:
    metadata:
      name: nginx-server
      labels:  # Corrected typo (labels instead of lables)
        type: server
        env: production
    spec:
      containers:
        - name: nginx-server
          image: nginx
